### ISSUE TITLE
order_create schema missing campaign

### ISSUE THREAD

**Issue by kehollin** [tangocarddev/RaaS#30]
Schema doesn't have a campaign element but the example does.

**Comment by bradyo** [comment]
Hi kehollin,
We are in the process of releasing an update to our API docs here: https://www.tangocard.com/docs/raas_api_reference/#create-order

The `campaign` field allows you to send reward e-mails for an order on different e-mail templates, which must be set up by a Customer Support Manager (there's currently no way to edit e-mail templates via the RaaS API). In most cases customers will have only 1 reward e-mail template, and not send the optional `campaign` field.

Hope that helps,
Closing the issue since it will be addressed in the next release of our API docs.

**Comment by kehollin** [comment]
Looking good! Don't forget expiration date in the reward object.

**Comment by kehollin** [comment]
Someone had stolen your documentation!

(Getting a 404 on the above link. :( )


Kevin Hollingshead
Research Software Engineer

*Arizona State University*
*College of Health Solutions*
*School of Nutrition and Health Promotion*
602-615-9972 (cell)
